return {
  -- {
  --   "nvim-telescope/telescope.nvim",
  --   dependencies = {
  --     {
  --       "nvim-telescope/telescope-live-grep-args.nvim",
  --       "nvim-telescope/telescope-fzf-native.nvim",
  --       build = "make",
  --       config = function()
  --         require("telescope").load_extension("live_grep_args")
  --         require("telescope").load_extension("fzf")
  --       end,
  --     },
  --   },
  --   opts = function(_, opts)
  --     local lga_actions = require("telescope-live-grep-args.actions")
  --
  --     opts.defaults = {
  --       require("telescope").setup({
  --         pickers = {
  --           find_files = {
  --             find_command = { "rg", "--hidden", "--files" },
  --             hidden = true,
  --           },
  --           live_grep = {
  --             auto_quoting = true, -- enable/disable auto-quoting
  --             mappings = { -- extend mappings
  --               i = {
  --                 ["<C-k>"] = lga_actions.quote_prompt(),
  --                 ["<C-i>"] = lga_actions.quote_prompt({ postfix = " --iglob " }),
  --                 ["<C-f>"] = require("telescope.actions").to_fuzzy_refine,
  --               },
  --             },
  --           },
  --         },
  --       }),
  --       path_display = {
  --         truncate = true,
  --       },
  --     }
  --     opts.extensions = {
  --       live_grep_args = {
  --         auto_quoting = true, -- enable/disable auto-quoting
  --         -- define mappings, e.g.
  --         mappings = { -- extend mappings
  --           i = {
  --             ["<C-k>"] = lga_actions.quote_prompt(),
  --             ["<C-i>"] = lga_actions.quote_prompt({ postfix = " --iglob " }),
  --             ["<C-f>"] = require("telescope.actions").to_fuzzy_refine,
  --           },
  --         },
  --         -- ... also accepts theme settings, for example:
  --         -- theme = "dropdown", -- use dropdown theme
  --         -- theme = { }, -- use own theme spec
  --         -- layout_config = { mirror=true }, -- mirror preview pane
  --       },
  --       fzf = {
  --         fuzzy = true, -- false will only do exact matching
  --         override_generic_sorter = true, -- override the generic sorter
  --         override_file_sorter = true, -- override the file sorter
  --         case_mode = "smart_case", -- or "ignore_case" or "respect_case"
  --         -- the default case_mode is "smart_case"
  --       },
  --     }
  --   end,
  --   keys = {
  --     {
  --       "<leader>/",
  --       ":lua require('telescope').extensions.live_grep_args.live_grep_args()<CR>",
  --       desc = "Grep (root dir)",
  --     },
  --     { "<C-M-/>", ":Telescope resume initial_mode=normal<CR>", desc = "Resume search" },
  --     { "<C-M-p>", ":Telescope git_status<CR>", desc = "Telescope git status" },
  --     {
  --       "<C-p>",
  --       ":Telescope find_files<CR>",
  --       desc = "Find files",
  --     },
  --     {
  --       "<leader>,",
  --       ":Telescope buffers theme=dropdown initial_mode=normal<CR>",
  --       desc = "Switch buffer",
  --     },
  --   },
  -- },
}
